name: Deploy HTML to Cloud


on:
   push:
      branches:
         - main    

jobs:
   deploy:
      runs-on: ubunto-latest
      steps:
         - name: CHeckout code
           uses: actions/checkout@v4


         - name: Show all files
           run: ls -ls

     
        

        
