name: Deploy HTML to Cloud


on:
   push:
      branches:
        - main    

job:
  deploy:
    runs-on: ubunto-latest

    steps:
    - name: CHeckout code
      uses: actions/checkout@v4


    - name: Show all files
      uses: ls -al

     
        

        
