name: Deploy HTML to Cloud


on:
   push:
      branches:
         - main    

jobs:
   deploy:
      runs-on: ubunto-latest
      steps:
         - name: CHeckout code
           uses: actions/checkout@v4


         - name: Show all files
           run: ls -ls

         - name: SSH to CLoud Server
           uses: appleboy/ssh-action@v1
           with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.CLOUD_USER }}
             password: ${{ secrets.CLOUD_SSH }}
             port: 22
             script: whoami


      

     
        

        
